### ISSUE TITLE
Tile behavior following ARN change

### ISSUE THREAD

**Issue by spainala** [aws-solutions/aws-media-services-application-mapper#158]
Please consider providing a method for identifying a tile or diagram that references a missing ARN.

In the event of an ARN change, an operator is not aware of a tile's broken diagram link until clicking the diagram button.

<img width="579" alt="Tile_prompt_following_ARN_change" src="https://user-images.githubusercontent.com/60242286/95896144-a60efc00-0d40-11eb-94cf-dc46084200dd.png">

**Comment by JimTharioAmazon** [comment]
@spainala I'm thinking of a little icon or symbol on the tile to indicate it doesn't have any matching diagrams. Would that work here?

**Comment by JimTharioAmazon** [comment]
Here is a peek of our UI prototyping for this one.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/33331284/160664438-60ae1c10-eab9-4aea-acaa-7aad444d7e79.png">

**Comment by JimTharioAmazon** [comment]
Tile view with diagram button in corner.

![image](https://user-images.githubusercontent.com/33331284/160932661-9a538c91-e04b-47a2-980a-5585d85dcd59.png)

Missing resources in the tile's contents are called out.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/33331284/160932790-30c3bbf4-535a-425f-accd-d54d140f2e83.png">

Selected item view for the tile shows the missing ARN list.

![image](https://user-images.githubusercontent.com/33331284/160935407-17ec821c-b712-493e-b2d9-f3feb96b66be.png)

The diagram button with range of matches.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/33331284/160933627-c891c959-37c8-48fa-8208-6911ff9358a6.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/33331284/160934962-d6666b78-2dc4-4a7f-b3ac-3328bb6745f7.png">

**Comment by spainala** [comment]
Great progress!  Visually illustrating a missing resource and pointing out the arn works well here. Two follow up questions.

1) How would an operator correct the diagram following an arn change?
2) How does the operator use the matching diagram score?

**Comment by JimTharioAmazon** [comment]
> Great progress! Visually illustrating a missing resource and pointing out the arn works well here. Two follow up questions.
> 
> 1. How would an operator correct the diagram following an arn change?
> 2. How does the operator use the matching diagram score?

The matching diagram % shows how much of a tile's contents is contained by the diagram. Read that dropdown list like, "Diagram X has 84% of this tile's contents." You can click in that dropdown to navigate to any of those diagrams, or create a new one from the tile's contents.

In a typical situation, you'd probably have at least one diagram in there at 100% match. If an ARN goes away after a resource change, the top matched diagrams might be less than 100% because of the deleted resource, but still referenced from the tile.

The operator can select one of those top-matched diagrams to navigate and use the Manage Diagram Contents dialog or Search to add the new resource. MSAM should automatically fill in connections when the new resource is added to the surface.

Diagrams will clean up missing ARN references in the background. Tiles will keep the missing ARN reference until you remove them using the edit tile menu option (or double-click the tile). See line 6 below in the image for the tile. Select that to remove and Save.

![image](https://user-images.githubusercontent.com/33331284/160942760-3bb95882-21a3-4a76-8451-1682b8c6486a.png)
